# Generated by Django 5.0 on 2023-12-26 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_rooms_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rooms",
            options={
                "ordering": ["-updated", "-created"],
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AlterModelTable(
            name="rooms",
            table="Room Table",
        ),
    ]
