# Generated by Django 5.0 on 2023-12-27 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_rooms_options_alter_rooms_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "Topic", "verbose_name_plural": "Topics"},
        ),
    ]
