# Generated by Django 5.0 on 2023-12-29 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_rooms_participants_alter_rooms_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={
                "ordering": ["-updated", "-created"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
